services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-greenlight}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    restart: always
    environment:
      MH_API_BIND_ADDR: ${MH_API_BIND_ADDR:-0.0.0.0:8025}
      MH_SMTP_BIND_ADDR: ${MH_SMTP_BIND_ADDR:-0.0.0.0:1025}
    ports:
      - "1025:1025"
      - "8025:8025"

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@db:5432/greenlight?sslmode=disable}
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     - db

volumes:
  postgres_data:
